# Generated by Django 4.1.6 on 2023-02-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_category_pub_date_category_category_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
